name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/page-1/images/favoritesduotone.png
    - assets/page-1/images/maplight.png
    - assets/page-1/images/maplight-eap.png
    - assets/page-1/images/undrawmobilepaymentsedgf-1.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/outline-interface-search.png
    - assets/page-1/images/union.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/outline-interface-history.png
    - assets/page-1/images/simple-line-icons-support.png
    - assets/page-1/images/emojione-check-mark-button.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/image-4-bg.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/image-5-bg.png
    - assets/page-1/images/image-4-bg-aXE.png
    - assets/page-1/images/photo.png
    - assets/page-1/images/ic-round-directions-car.png
    - assets/page-1/images/fa-solid-parking.png
    - assets/page-1/images/maplight-E9z.png
    - assets/page-1/images/navigation-menu-home.png
    - assets/page-1/images/message.png
    - assets/page-1/images/ei-close-o.png
    - assets/page-1/images/fa-solid-parking-zYL.png
    - assets/page-1/images/feather-settings.png
    - assets/page-1/images/solid-interface-cursor.png
    - assets/page-1/images/gridicons-location.png
    - assets/page-1/images/maplight-x1i.png
    - assets/page-1/images/favoritesduotone-nuA.png
    - assets/page-1/images/pagination-light.png
    - assets/page-1/images/image-4-bg-8J8.png
    - assets/page-1/images/ps-promo.png
    - assets/page-1/images/ei-close.png
    - assets/page-1/images/photo-FpQ.png
    - assets/page-1/images/solid-navigation-location.png
    - assets/page-1/images/photo-h24.png
    - assets/page-1/images/solid-status-star.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/photo-tXe.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/auto-group-axdw.png
    - assets/page-1/images/maplight-mQp.png
    - assets/page-1/images/favoritesduotone-xGt.png
    - assets/page-1/images/outline-interface-history-2pL.png
    - assets/page-1/images/pagination-light-zo6.png
    - assets/page-1/images/solid-interface-cursor-17r.png
    - assets/page-1/images/solid-interface-cursor-XU8.png
    - assets/page-1/images/outline-brands-apple.png
    - assets/page-1/images/icon-settings-privacypolicy.png
    - assets/page-1/images/fa-regular-edit.png
    - assets/page-1/images/fa-solid-parking-aUC.png
    - assets/page-1/images/icon-settings-notifications.png
    - assets/page-1/images/ic-round-directions-car-1qN.png
    - assets/page-1/images/ic-round-directions-car-CVA.png
    - assets/page-1/images/emojione-check-mark-button-qwz.png
    - assets/page-1/images/vector-M9e.png
    - assets/page-1/images/vector-Y6x.png
    - assets/page-1/images/arrowleft.png
    - assets/page-1/images/group.png
    - assets/page-1/images/solid-interface-cursor-xAY.png
    - assets/page-1/images/undrawmaplight3hjy-1.png
    - assets/page-1/images/solid-navigation-explore.png
    - assets/page-1/images/maplight-msr.png
    - assets/page-1/images/parkenlogin.png
    - assets/page-1/images/ic-round-directions-car-dMe.png
    - assets/page-1/images/fa-solid-parking-xpU.png
    - assets/page-1/images/solid-navigation-explore-SzY.png
    - assets/page-1/images/fa-solid-parking-uVN.png
    - assets/page-1/images/icon-settings-termsofuse.png
    - assets/page-1/images/vector-1RE.png
    - assets/page-1/images/favoritesduotone-Cck.png
    - assets/page-1/images/favoritesduotone-34G.png
    - assets/page-1/images/ic-round-directions-car-66p.png
    - assets/page-1/images/auto-group-fjty.png
    - assets/page-1/images/google.png
    - assets/page-1/images/maplight-uqv.png
    - assets/page-1/images/union-EBv.png
    - assets/page-1/images/solid-navigation-explore-tvg.png
    - assets/page-1/images/ic-outline-payment.png
    - assets/page-1/images/ic-round-directions-car-QCk.png
    - assets/page-1/images/vector-mFS.png
    - assets/page-1/images/solid-interface-cursor-mXS.png
    - assets/page-1/images/favoritesduotone-stQ.png
    - assets/page-1/images/outline-interface-caret-down.png
    - assets/page-1/images/ic-round-history.png
    - assets/page-1/images/icon-settings-language.png
    - assets/page-1/images/fa-solid-parking-7qE.png
    - assets/page-1/images/auto-group-zrex.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/vector-GPe.png
    - assets/page-1/images/navigation-menu-home-pUL.png
    - assets/page-1/images/ls-logout.png
    - assets/page-1/images/ic-round-directions-car-tGL.png
    - assets/page-1/images/fa-solid-parking-CMJ.png
    - assets/page-1/images/navigation-menu-home-h9W.png
    - assets/page-1/images/arrowdropdownbig.png
    - assets/page-1/images/solid-interface-cursor-Jkt.png
    - assets/page-1/images/favoritesduotone-nZJ.png
    - assets/page-1/images/auto-group-8bvl.png
    - assets/page-1/images/ic-round-directions-car-LEQ.png
    - assets/page-1/images/solid-interface-other-1.png
    - assets/page-1/images/facebook.png
    - assets/page-1/images/vector-Zcg.png
    - assets/page-1/images/gridicons-location-aEY.png
    - assets/page-1/images/solid-interface-cursor-kvp.png
    - assets/page-1/images/solid-interface-other-1-Fe4.png
    - assets/page-1/images/octicon-info.png
    - assets/page-1/images/undrawcitydriverjh2h-1.png
    - assets/page-1/images/navigation-menu-home-qXr.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
